// Generated by gencpp from file erica_arm_module_msgs/ArmCmd.msg
// DO NOT EDIT!


#ifndef ERICA_ARM_MODULE_MSGS_MESSAGE_ARMCMD_H
#define ERICA_ARM_MODULE_MSGS_MESSAGE_ARMCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace erica_arm_module_msgs
{
template <class ContainerAllocator>
struct ArmCmd_
{
  typedef ArmCmd_<ContainerAllocator> Type;

  ArmCmd_()
    : name()
    , pose()
    , time(0.0)  {
    }
  ArmCmd_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pose(_alloc)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ArmCmd_

typedef ::erica_arm_module_msgs::ArmCmd_<std::allocator<void> > ArmCmd;

typedef boost::shared_ptr< ::erica_arm_module_msgs::ArmCmd > ArmCmdPtr;
typedef boost::shared_ptr< ::erica_arm_module_msgs::ArmCmd const> ArmCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace erica_arm_module_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'erica_arm_module_msgs': ['/home/erica-nuc/catkin_ws/src/ERICA/HERoEHS-ERICA-msgs/erica_arm_module_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "995a32c00b8b6956d8f616746f81ea12";
  }

  static const char* value(const ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x995a32c00b8b6956ULL;
  static const uint64_t static_value2 = 0xd8f616746f81ea12ULL;
};

template<class ContainerAllocator>
struct DataType< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erica_arm_module_msgs/ArmCmd";
  }

  static const char* value(const ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string    	   name\n\
geometry_msgs/Pose pose\n\
float64            time\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pose);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erica_arm_module_msgs::ArmCmd_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERICA_ARM_MODULE_MSGS_MESSAGE_ARMCMD_H
